insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');
insert into statistics(page_Traffic, time, audio_Counter, print_Time) values (0, 0, 0, '00:00:00');

insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Posljednja večera', 'Posljednja večera Leonarda da Vincija jedno je od najvećih svjetskih umjetničkih remek-djela. Unatoč jadnom stanju ova slika je postala ikonom kršćanskog slikarstva i jedna od najpoznatijih slika na svijetu. Njezin uspjeh potječe iz Leonardove sposobnosti prikazivanja karaktera i dramatične napetosti, te njihovim smještanjem u dominantan i ujedinjujući arhitektonski interijer.', '1.jpg', '1.mp3', 1, 'Renesansa', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Rođenje Venere', 'Sandro Botticelli (1445.-1510.) je svoju sliku Rođenje Venere naslikao u seriji mitoloških slika za obitelj Medici koji su se zanimali za pogansku tematiku. To zanimanje je potaknuto obnovom Platonove filozofije (Neoplatonizam) koja je dovela do zanimanja za antičke teme i osnivanje Platonove Akademije u Firenci 1469. god.', '2.jpg', '2.mp3', 2, 'Renesansa', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Atenska Škola', 'Atensku školu je Rafael naslikao u svom kasnijem stilu u kojemu su slike slikane u velikim dimenzijama, s brojnim likovima u pokretu i snažnim svjetlom i sjenama. Rafael je, kao niti jedan renesansni slikar, kombinirao klasičnu jasnoću s kršćanskom tradicijom s velikom lakoćom stvaranja. Također je kombinirao Leonardovo slikarstvo s likovima u geometrijskim kompozicijama, kjaroskurom, sfumatom i atmosferskom perspektivom s Michelangelovim bojama i snažnim likovima. Njegovo najpoznatije djelo je upravo Atenska Škola.', '3.jpg', '3.mp3', 3, 'Renesansa', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Oplakivanje Krista', 'Oplakivanje Krista (poznata i kao Plač iznad mrtvog Krista ili jednostavno Mrtvi Krist) je slika ranorenesansnog talijanskog slikara Andree Mantegna iz oko 1480. godine (iako datiranje slike nije pouzdano utvrđeno, zasigurno se zna da je naslikana nekad između 1475. i 1501. god., najvjerojatnije ranih 1480-ih). Slika prikazuje tijelo mrtvog Krista, položeno na mramornu ploču, dok ga promatraju Djevica Marija i Sveti Ivan, koji oplakuju njegovu smrt.', '4.jpg', '4.mp3', 4, 'Renesansa', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Noćna Straža', 'Polovicom svoje karijere, Rembrandt je postao vodeći portretist u Amsterdamu, a s obzirom kako je u protestantskoj Nizozemskoj crkveno sponzorstvo bilo u padu, zamijenile su ga svjetovne skupine poput liječnika, vojnika ili upravitelja nekih ustanova. Rembrandt je Noćnu stražu upravo uradio za jednu vojnu skupinu (arkebuzirsku četu) koja je održavala mir u slobodnom gradu Amsterdamu i izvorno je stajala u odajama amsterdamske civilne zaštite.', '5.jpg', '5.mp3', 5, 'Barok', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Pozivanje Svetog Mateja', 'Pozivanje Svetog Mateja je slavno ulje na platnu Caravaggia iz oko 1597. godine; remek-djelo koje se smatra prvim djelom baroka. Naslikano je za kapelu Contarelli u crkvi San Luigi dei Francesi (Sveti Lujo Francuski) u Rimu gdje se i danas nalazi.', '6.jpg', '6.mp3', 6, 'Barok', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Las Meninas', 'Las Meninas (španjolski za: Male dvorske dame) je monumentalno ulje na platnu iz 1656. godine; najveće remek-djelo španjolskog baroknog slikara Velázqueza. Ova slika ne služi samo na počast Velázquezovoj genijalnosti, nego i samome slikarstvu kao umjetnosti.Las Meninas je prepoznata kao jedna od najvažnijih slika u Europskom slikarstvu. Barokni slikar Luca Giordano ju je nazvao "teologijom slikarstva".', '7.jpg', '7.mp3', 7, 'Barok', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Suncokreti', 'Suncokreti (francuski: Tournesols) su motiv dvije serija slika i crteža nizozemskog slikara Vincenta van Gogha. Prva serija slika, naslikana u Parizu 1887., predstavlja polegnute suncokrete, za razliku od druge serije, nastale u Arlesu godinu dana kasnije, koja predstavlja buket suncokreta u vazi.', '8.jpg', '8.mp3', 8, 'Kasni novi vijek', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Žena sa suncobranom', 'Žena sa suncobranom (fra.: La Promenade), poznata i kao Gđa. Monet i njezin sin, je slika Claudea Moneta, najdosljednijeg francuskog slikara impresionizma, koja je nastala prilikom njegova obiteljskog izleta u Argenteuil 1875. godine.', '9.jpg', '9.mp3', 9, 'Kasni novi vijek', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Ljuljačka', 'Ljuljačka (francuski: LEscarpolette), izvornog naziva Sretne nezgode na ljuljački (Les Hasards Heureux de lEscarpolette) je slavno ulje na platnu i najslavnije djelo rokoko slikara Jean-Honoréa Fragonarda (1732.-1806.). Ovu sliku je uvelike cijenila umjetnička kritika njegovog doba, poput najslavnijeg kritičara Denisa Diderota i u to vrijeme je njegovo slikarstvo povezivano s lascivnim spolnim izražavanjem koje graniči s pornografijom.', '10.jpg', '10.mp3', 10, 'Kasni novi vijek', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Glazba u Tulleriasu', 'Polovicom svoje karijere, Rembrandt je postao vodeći portretist u Amsterdamu, a s obzirom kako je u protestantskoj Nizozemskoj crkveno sponzorstvo bilo u padu, zamijenile su ga svjetovne skupine poput liječnika, vojnika ili upravitelja nekih ustanova. Rembrandt je Noćnu stražu upravo uradio za jednu vojnu skupinu (arkebuzirsku četu) koja je održavala mir u slobodnom gradu Amsterdamu i izvorno je stajala u odajama amsterdamske civilne zaštite.', '11.jpg', '11.mp3', 11, 'Kasni novi vijek', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Gospođice iz Avignona', 'Gospođice iz Avignona (francuski:Les Demoiselles dAvignon) je revolucionarno ulje na platnu Pabla Picassa, koje je naslikao od lipnja do srpnja 1907. godine, a koje se smatra prvom kubističkom, avangardnom, i općenito modernom slikom 20. stoljeća. S ovim prikazom pet ženskih aktova s mrtvom prirodom Picasso je pokrenuo prostornu revoluciju u slikarstvu.', '12.jpg', '12.mp3', 12, 'Moderna umjetnost', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Postojanost pamćenja', 'Postojanost pamćenja (španjolski: La persistencia de la memoria, katalonski: La persistència de la memòria) je slavno ulje na platnu španjolskog nadrealističkog slikara Salvadora Dalíja iz 1931. godine. Jedno od njegovih najpoznatijih djela prvi put je prikazano u galeriji Julien Levy u New Yorku 1932. god., a od 1934. god. nalazi se u trajnom posjedu Muzeja moderne umjetnosti u New Yorku.', '13.jpg', '13.mp3', 13, 'Moderna umjetnost', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Broj 5', 'Postojanost pamćenja (španjolski: La persistencia de la memoria, katalonski: La persistència de la memòria) je slavno ulje na platnu španjolskog nadrealističkog slikara Salvadora Dalíja iz 1931. godine. Jedno od njegovih najpoznatijih djela prvi put je prikazano u galeriji Julien Levy u New Yorku 1932. god., a od 1934. god. nalazi se u trajnom posjedu Muzeja moderne umjetnosti u New Yorku.', '14.jpg', '14.mp3', 14, 'Moderna umjetnost', true);
insert into museum_object(name, description, image_Name, audio_Name, statistics_id, group_Of_Museum_Objects, in_Museum) values ('Autoportret s ogrlicom od trnja', 'Rođena je u Ciudad Méxicu 6. srpnja 1907. kao Magdalena Carmen Frieda Kahlo y Calderón; treća kćer Guillerma (Karla Wilhelma) Kahla, fotografa židovskog podrijetla iz Njemačke, i Matilde Calderón y González, Španjolke rođene u Americi. God. 1922. upisala se na Nacionalnu pripremnu školu, najprestižniju obrazovnu instituciju u Meksiku, koja je upravo tada počela primati djevojke. Tamo je upoznala budućeg muža, Diega Riveru uz kojega je prihvatila komunističku ideologiju.', '15.jpg', '15.mp3', 15, 'Moderna umjetnost', true);

insert into role(name) values ('Vlasnik sustava');
insert into role(name) values ('Administrator');
insert into role(name) values ('Registrirani korisnik');
insert into role(name) values ('Neregistrirani korisnik');

insert into users(username, first_Name, last_Name, email, password_Hash, role_id, currently_Active, account_Confirmed) 
values ('a', 'Pero', 'Peric', 'pero@gmail.com', '86f7e437faa5a7fce15d1ddcb9eaeaea377667b8', 1, false, true);
insert into users(username, first_Name, last_Name, email, password_Hash, role_id, currently_Active, account_Confirmed) 
values ('admin1', 'Ante', 'Ante', 'ante@gmail.com', '86f7e437faa5a7fce15d1ddcb9eaeaea377667b8', 2, false, true);
insert into users(username, first_Name, last_Name, email, password_Hash, role_id, currently_Active, account_Confirmed) 
values ('admin2', 'Borna', 'Borna', 'borna@gmail.com', '86f7e437faa5a7fce15d1ddcb9eaeaea377667b8', 2, false, true);
insert into users(username, first_Name, last_Name, email, password_Hash, role_id, currently_Active, account_Confirmed) 
values ('kor1', 'Dora', 'Dora', 'dora@gmail.com', '86f7e437faa5a7fce15d1ddcb9eaeaea377667b8', 3, false, true);
insert into users(username, first_Name, last_Name, email, password_Hash, role_id, currently_Active, account_Confirmed) 
values ('kor2', 'Eva', 'Eva', 'eva@gmail.com', '86f7e437faa5a7fce15d1ddcb9eaeaea377667b8', 3, false, true);
